version: "3.9"

services:
  yolo-service:
    build: .
    container_name: yolo-service
    command: python -m services.yolo.cli --image docs/examples/apple.jpg
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 4g